### ISSUE TITLE
Looking for interactions in treatments from TreatmentBank

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/tick-interaction-database#1]
It is unclear what the best workflow to extract interactions from a work already processed through Treatment Bank. See http://tb.plazi.org/GgServer/summary/9A0A221A5A64A83CFFD6FFAEFFE6FFCF

How to keep track of which treatments have been examined when evaluated by multiple people.

**Comment by jhpoelen** [comment]
@seltmann good to see the tick interaction database pop up! 

About this workflow issue - is this a question or a note to self?

**Comment by seltmann** [comment]
@jhpoelen I am looking for input and there are a few issues about this. For example, if you look at Treatment bank http://tb.plazi.org/GgServer/html/546287D7313C3F6AC9ACF9F1FF5DF9A2 you get statements like: 

15) Amblyomma parvum Aragão, 1908 a is a Neotropical species. Adult ticks have an ample host range, but Rodentia: Caviidae Fischer de Waldheim are the usual hosts for their larvae and nymphs (Nava et al. 2008).

The interaction is Amblyomma parvum Aragão, 1908 has host Caviidae Fischer de Waldheim, but the citation for this is not Guglielmone, et al. 2011 it is Nava et al. 2008. But I assume the TreatmentBank link should still be http://tb.plazi.org/GgServer/html/546287D7313C3F6AC9ACF9F1FF5DF9A2

**Comment by seltmann** [comment]
@jhpoelen Basically I think we should avoid citing derivative works unless making sure it is known that it is derived from another source.

**Comment by seltmann** [comment]
@jhpoelen Also, if you start with the root by searching for the paper (http://tb.plazi.org/GgServer/summary/9A0A221A5A64A83CFFD6FFAEFFE6FFCF) how do you find all of the treatments in a logical way in the paper? I am not sure how to organize students to get information from TreatmentBank for each treatment.

**Comment by jhpoelen** [comment]
hey @seltmann - thanks for providing the examples and ideas on recording the provenance of an interaction claim. I'll share some ideas below an perhaps our Plazi colleagues @myrmoteras  @mguidoti can chime in too. 

> Amblyomma parvum Aragão, 1908 a is a Neotropical species. Adult ticks have an ample host range, but Rodentia: Caviidae Fischer de Waldheim are the usual hosts for their larvae and nymphs (Nava et al. 2008).

In your example,  http://tb.plazi.org/GgServer/summary/9A0A221A5A64A83CFFD6FFAEFFE6FFCF contains the claim that ```Amblyomma parvum Aragão, 1908 (lifestage: adult/larvae/nymphs) has host Rodentia: Caviidae Fischer de Waldheim``` and references Nava et al. 2008 as the authority. So, I'd say that both Guglielmone, et al. 2011 and  Nava et al. 2008 should be cited since they both make the claim (assuming that Nava et al. 2008 actually makes that claim). The basis of record for the first claim would be a literature record, and the second (Nava et al. 2008) might be something else, like a PreservedSpecimen of human observations.


> @jhpoelen Also, if you start with the root by searching for the paper (http://tb.plazi.org/GgServer/summary/9A0A221A5A64A83CFFD6FFAEFFE6FFCF) how do you find all of the treatments in a logical way in the paper? I am not sure how to organize students to get information from TreatmentBank for each treatment.

Not quite sure how to answer this question. Perhaps Marcus and/or Donat have some insight on how to parse out and reference specific species descriptions/revisions from a "bulk" revision such as the Guglielmone, et al. 2011 provides for ticks. From this example, I can see that Guglielmone, et al. 2011 was split into three parts Argasidae, Ixodidae and Nuttalliellidae, each containing long lists of associated species names.

**Comment by seltmann** [comment]
Conversation moved to: [https://github.com/plazi/community/issues/59](https://github.com/plazi/community/issues/59)
